### ISSUE TITLE
skyux help displays distorted header info box 

### ISSUE THREAD

**Issue by v-amityadav** [blackbaud/skyux-sdk-cli#101]
Repro Steps
1. Run `skyux help`
2. Now look Header info box is distorted as in attached SS :)

![image](https://user-images.githubusercontent.com/59632461/92994360-28748800-f517-11ea-8cd1-54df83639087.png)

**Comment by Blackbaud-DanMiller** [comment]
Sorry - this is not a priority to fix for us at the moment. Feel free to contribute following our guidelines: https://developer.blackbaud.com/skyux/contribute
