### ISSUE TITLE
skyux new hangs on repo cloning step

### ISSUE THREAD

**Issue by Blackbaud-ErikaMcVey** [blackbaud/skyux-sdk-cli#102]
After you create a new SPA and clone the repo locally it hangs forever. If you run `skyux new` locally and then `git init` there are no issues.

**Comment by Blackbaud-SteveBrush** [comment]
`git clone [ADO-generated repo]` hangs for several minutes. This is more than likely a problem with Engineering System SPA, not the  SKY UX CLI.
