### ISSUE TITLE
skyux install hides npm auth exception errors

### ISSUE THREAD

**Issue by Blackbaud-CoreyArcher** [blackbaud/skyux-sdk-cli#23]
**Expected Behavior**
When running `skyux install`, issues such as npm authentication errors should be made clear so the user knows that they should renew their certification for npm to function correctly.

**Actual Behavior**
The install process fails to complete when running `skyux install`, and returns the following error message:
> (node:16440) UnhandledPromiseRejectionWarning: npm install failed.
> (node:16440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:16440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Impact**
User's have to use `npm install` to see the error details, in order to understand why the install process failed.

**Severity**
Low

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed in #25 and #11.
Released in [3.1.0](https://github.com/blackbaud/skyux-sdk-cli/blob/master/CHANGELOG.md#310-2019-05-08).
