### ISSUE TITLE
Add skyux upgrade command to the CLI

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-sdk-cli#27]
Move the command from the migrate utility to the CLI.

**Comment by Blackbaud-BobbyEarl** [comment]
Work to release:

- [ ] https://github.com/blackbaud/skyux-sdk-cli/pull/35 (@Blackbaud-MatthewMiles)
- [ ] https://github.com/blackbaud/skyux-sdk-builder-plugin-migrate/pull/74

**Comment by Blackbaud-BobbyEarl** [comment]
Released in [3.4.0](https://github.com/blackbaud/skyux-sdk-cli/blob/master/CHANGELOG.md#340-2020-01-22).  
[Documented](https://developer.blackbaud.com/skyux/learn/reference/cli-commands/upgrade) via [#813](https://github.com/blackbaud/skyux2-docs/pull/813).
