### ISSUE TITLE
Document `libnss3-tools` requirement for Linux.

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-sdk-cli#43]
In order to successfully trust the cert in Chrome on Linux, we use `certutil`, which comes from the `libnss3-tools` package.

```
# Debian, Ubuntu, Mint, etc.
sudo apt-get install libnss3-tools

# Fedora, Red Hat, etc.
sudo yum install nss-tools 
```

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/735.
