### ISSUE TITLE
`skyux new` for library should have correct prompt

### ISSUE THREAD

**Issue by Blackbaud-DiHuynh** [blackbaud/skyux-sdk-cli#49]
The prompt for creating a library is just a bit confusing since the prompt says SPA.
 ```
$ sky new -t library
SKY UX is processing the 'new' command.
What is the root directory for your SPA? (example: my-spa-name) foo
Creating a new SPA named 'skyux-lib-foo'.
```
I'd like to contribute this tiny feature if that's ok with the Skyux team

**Comment by Blackbaud-BobbyEarl** [comment]
Addressed in #48.
Released in [`3.3.0`](https://github.com/blackbaud/skyux-sdk-cli/blob/master/CHANGELOG.md#330-2019-12-06)
