### ISSUE TITLE
Update 'update-notifier' to indicate global

### ISSUE THREAD

**Issue by Blackbaud-MatthewMiles** [blackbaud/skyux-sdk-cli#60]
When running the 'version' command, you may be prompted to update.  This message should probably be modified to include the '-g' flag so that the user does not accidentally (or without knowing any better) install the cli as a dependency on their SPA.

e.g.
![image](https://user-images.githubusercontent.com/16880251/74194466-4ac3c180-4c27-11ea-9543-73f85a693476.png)

**Comment by Blackbaud-MatthewMiles** [comment]
I _may_ be able to contribute this

**Comment by Blackbaud-MatthewMiles** [comment]
Bobby Earl is too fast!

**Comment by Blackbaud-BobbyEarl** [comment]
Released in [`3.4.2`](https://github.com/blackbaud/skyux-sdk-cli/blob/master/CHANGELOG.md#342-2020-02-11)
